from typing import Literal, TypeAlias

import numpy as np
from numpy.typing import NDArray

Schedule: TypeAlias = NDArray[np.int32]
Distances: TypeAlias = NDArray[np.int32]
NeighborhoodName: TypeAlias = Literal[
    "swap_homes",
    "swap_rounds",
    "swap_teams",
    "partial_swap_rounds",
    "partial_swap_teams",
]

def objective(schedule: Schedule, distances: Distances) -> int: ...
def satisfies_stand_limits(schedule: Schedule, max_k: int) -> bool: ...
def has_repeaters(schedule: Schedule) -> bool: ...
def is_valid_schedule(schedule: Schedule) -> bool: ...
def swap_homes(schedule: Schedule, i: int, j: int) -> Schedule: ...
def swap_rounds(schedule: Schedule, r1: int, r2: int) -> Schedule: ...
def swap_teams(schedule: Schedule, i: int, j: int) -> Schedule: ...
def partial_swap_rounds(schedule: Schedule, team: int, r1: int, r2: int) -> Schedule: ...
def partial_swap_teams(schedule: Schedule, i: int, j: int, round: int) -> Schedule: ...
def local_search_step(
    schedule: Schedule, distances: Distances, max_k: int
) -> list[tuple[NeighborhoodName, int, Schedule]]: ...
